server:
  port: 8074
spring:
  application:
    name: microservice-gateway-zuul

  cloud:
    config:
      server:
        git:
          # Git仓库地址
          uri: https://github.com/zhangyaodong123/itmuch.git
          # Git仓库账号
          username: zhangyaodong123
          # Git仓库密码
          password: aaa19921003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

zuul:
  routes:
    user-provider: /user/**
